import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/react";
import ContentFrame from "@/components/explore/content-frame";
import {UserAvatar} from "@/components/explore/userAvatar";
import {Button} from "@/components/ui/button";
import Link from "next/link";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}>
            <section className={"w-full h-20"}>
                <ContentFrame className={"h-full flex flex-row justify-between items-center"}>
                    <h1 className={"text-2xl font-bold"}><Link href={"/"}>Homely</Link></h1>
                    <div className={"flex flex-row gap-6 items-center"}>
                        <Link href={"/travel"} className={"font-bold hover:bg-accent hover:text-accent-foreground h-9 px-4 py-2 rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0"}>Your reservations</Link>
                        <UserAvatar userAvatarUrl={""}/>
                    </div>
                </ContentFrame>
            </section>
            <NextUIProvider>
                <section className={"w-full h-[calc(100vh-5rem)]"}>
                    {children}
                </section>
            </NextUIProvider>
        </body>
        </html>
    );
}
