import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/react";
import ContentFrame from "@/components/explore/content-frame";
import {UserAvatar} from "@/components/explore/userAvatar";
import {Button} from "@/components/ui/button";
import {router} from "next/client";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}>
            <section className={"w-full h-20"}>
                <ContentFrame className={"h-full flex flex-row justify-between items-center"}>
                    <h1 className={"text-2xl font-bold"}>Homely</h1>
                    <div className={"flex flex-row gap-6 items-center"}>
                        <Button variant={"ghost"} onClick={{/*() => router.push('/reservations')*/}}>Your reservations</Button>
                        <UserAvatar userAvatarUrl={""}/>
                    </div>
                </ContentFrame>
            </section>
            <NextUIProvider>
                <section className={"w-full h-[calc(100vh-5rem)]"}>
                    {children}
                </section>
            </NextUIProvider>
        </body>
        </html>
    );
}
